trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

# strategy:
#   matrix:
#     Python38:
#       python.version: '3.8'

stages:
  - stage: devevlopmentDeployment
    displayName: Deploy dbx notebooks to Dev
    variables:
      - group: development


    jobs:
      - deployment: deployHeaderFooterNotebooks
        displayName: Deploy Dbx Notebooks
        environment: 'development'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: ../ci/templates/notebook.yml
                  parameters:
                    azureResourceManagerConnection: 'development_subscription'
                    keyVaultName: '$(KEY_VAULT)'
                    SubscriptionId: '$(SUBSCRIPTION_ID)'
                    ResourceGroup: '$(RESOURCE_GROUP)'
                    DbxWorkspaceName: '$(DATABRICKS_WORKSPACE_NAME)'
                    DbxWorkspaceUrl: '$(DATABRICKS_WORKSPACE_URL)'
                    DbxWorkspaceSubDirs: '$(DATABRICKS_WORKSPACE_SUBDIRS)'
                    DbxWorkspaceRoot: '$(DATABRICKS_WORKSPACE_ROOT)'
                    FromWorkspaceDir: 'header_footer'
                    ToWorkspaceDir: 'header_footer'

      - deployment: deployAdWorksLtNotebooks
        displayName: Deploy AdWorksLt Notebooks
        environment: 'development'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: ../ci/templates/notebook.yml
                  parameters:
                    azureResourceManagerConnection: 'development_subscription'
                    keyVaultName: '$(KEY_VAULT)'
                    SubscriptionId: '$(SUBSCRIPTION_ID)'
                    ResourceGroup: '$(RESOURCE_GROUP)'
                    DbxWorkspaceName: '$(DATABRICKS_WORKSPACE_NAME)'
                    DbxWorkspaceUrl: '$(DATABRICKS_WORKSPACE_URL)'
                    DbxWorkspaceSubDirs: '$(DATABRICKS_WORKSPACE_SUBDIRS)'
                    DbxWorkspaceRoot: '$(DATABRICKS_WORKSPACE_ROOT)'
                    FromWorkspaceDir: 'ad_works_lt'
                    ToWorkspaceDir: 'ad_works_lt'

      - deployment: deployAdWorksNotebooks
        displayName: Deploy AdWorks Notebooks
        environment: 'development'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: ../ci/templates/notebook.yml
                  parameters:
                    azureResourceManagerConnection: 'development_subscription'
                    keyVaultName: '$(KEY_VAULT)'
                    SubscriptionId: '$(SUBSCRIPTION_ID)'
                    ResourceGroup: '$(RESOURCE_GROUP)'
                    DbxWorkspaceName: '$(DATABRICKS_WORKSPACE_NAME)'
                    DbxWorkspaceUrl: '$(DATABRICKS_WORKSPACE_URL)'
                    DbxWorkspaceSubDirs: '$(DATABRICKS_WORKSPACE_SUBDIRS)'
                    DbxWorkspaceRoot: '$(DATABRICKS_WORKSPACE_ROOT)'
                    FromWorkspaceDir: 'ad_works'
                    ToWorkspaceDir: 'ad_works'

      - deployment: deployAdWorksDWNotebooks
        displayName: Deploy AdWorks DW Notebooks
        environment: 'development'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: ../ci/templates/notebook.yml
                  parameters:
                    azureResourceManagerConnection: 'development_subscription'
                    keyVaultName: '$(KEY_VAULT)'
                    SubscriptionId: '$(SUBSCRIPTION_ID)'
                    ResourceGroup: '$(RESOURCE_GROUP)'
                    DbxWorkspaceName: '$(DATABRICKS_WORKSPACE_NAME)'
                    DbxWorkspaceUrl: '$(DATABRICKS_WORKSPACE_URL)'
                    DbxWorkspaceSubDirs: '$(DATABRICKS_WORKSPACE_SUBDIRS)'
                    DbxWorkspaceRoot: '$(DATABRICKS_WORKSPACE_ROOT)'
                    FromWorkspaceDir: 'ad_works_dw'
                    ToWorkspaceDir: 'ad_works_dw'

      - deployment: deployHeaderFooterWorkflows
        displayName: Deploy Dbx header_footer Workflows
        environment: 'development'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: ../ci/templates/workflows.yml
                  parameters:
                    azureResourceManagerConnection: 'development_subscription'
                    keyVaultName: '$(KEY_VAULT)'
                    SubscriptionId: '$(SUBSCRIPTION_ID)'
                    ResourceGroup: '$(RESOURCE_GROUP)'
                    DbxWorkspaceName: '$(DATABRICKS_WORKSPACE_NAME)'
                    DbxWorkspaceUrl: '$(DATABRICKS_WORKSPACE_URL)'
                    DbxWorkspaceRoot: '$(DATABRICKS_WORKSPACE_ROOT)'
                    SubDir: 'header_footer/databricks/workflows'


      - deployment: deployAdWorksWorkflows
        displayName: Deploy Dbx ad_works Workflows
        environment: 'development'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: ../ci/templates/workflows.yml
                  parameters:
                    azureResourceManagerConnection: 'development_subscription'
                    keyVaultName: '$(KEY_VAULT)'
                    SubscriptionId: '$(SUBSCRIPTION_ID)'
                    ResourceGroup: '$(RESOURCE_GROUP)'
                    DbxWorkspaceName: '$(DATABRICKS_WORKSPACE_NAME)'
                    DbxWorkspaceUrl: '$(DATABRICKS_WORKSPACE_URL)'
                    DbxWorkspaceRoot: '$(DATABRICKS_WORKSPACE_ROOT)'
                    SubDir: 'ad_works/databricks/workflows
'
      - deployment: deployAdWorksLtWorkflows
        displayName: Deploy Dbx ad_works lt Workflows
        environment: 'development'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: ../ci/templates/workflows.yml
                  parameters:
                    azureResourceManagerConnection: 'development_subscription'
                    keyVaultName: '$(KEY_VAULT)'
                    SubscriptionId: '$(SUBSCRIPTION_ID)'
                    ResourceGroup: '$(RESOURCE_GROUP)'
                    DbxWorkspaceName: '$(DATABRICKS_WORKSPACE_NAME)'
                    DbxWorkspaceUrl: '$(DATABRICKS_WORKSPACE_URL)'
                    DbxWorkspaceRoot: '$(DATABRICKS_WORKSPACE_ROOT)'
                    SubDir: 'ad_works_lt/databricks/workflows'

      - deployment: deployAdWorksDWWorkflows
        displayName: Deploy Dbx ad_works_dw Workflows
        environment: 'development'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: ../ci/templates/workflows.yml
                  parameters:
                    azureResourceManagerConnection: 'development_subscription'
                    keyVaultName: '$(KEY_VAULT)'
                    SubscriptionId: '$(SUBSCRIPTION_ID)'
                    ResourceGroup: '$(RESOURCE_GROUP)'
                    DbxWorkspaceName: '$(DATABRICKS_WORKSPACE_NAME)'
                    DbxWorkspaceUrl: '$(DATABRICKS_WORKSPACE_URL)'
                    DbxWorkspaceRoot: '$(DATABRICKS_WORKSPACE_ROOT)'
                    SubDir: 'ad_works_dw/databricks/workflows'