trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

# strategy:
#   matrix:
#     Python38:
#       python.version: '3.8'

stages:
  - stage: devevlopmentDeployment
    displayName: Deploy dbx notebooks to Dev
    variables:
      - group: development


    jobs:
      - deployment: deployNotebooks
        displayName: Deploy Dbx Notebooks
        environment: 'development'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: ../ci/templates/notebook.yml
                  parameters:
                    azureResourceManagerConnection: 'development_subscription'
                    keyVaultName: '$(KEY_VAULT)'
                    SubscriptionId: '$(SUBSCRIPTION_ID)'
                    ResourceGroup: '$(RESOURCE_GROUP)'
                    DbxWorkspaceName: '$(DATABRICKS_WORKSPACE_NAME)'
                    DbxWorkspaceUrl: '$(DATABRICKS_WORKSPACE_URL)'
                    DbxWorkspaceSubDirs: '$(DATABRICKS_WORKSPACE_SUBDIRS)'
                    DbxWorkspaceRoot: '$(DATABRICKS_WORKSPACE_ROOT)'

      - deployment: deployHeaderFooterWorkflows
        displayName: Deploy Dbx header_footer Workflows
        environment: 'development'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: ../ci/templates/workflows.yml
                  parameters:
                    azureResourceManagerConnection: 'development_subscription'
                    keyVaultName: '$(KEY_VAULT)'
                    SubscriptionId: '$(SUBSCRIPTION_ID)'
                    ResourceGroup: '$(RESOURCE_GROUP)'
                    DbxWorkspaceName: '$(DATABRICKS_WORKSPACE_NAME)'
                    DbxWorkspaceUrl: '$(DATABRICKS_WORKSPACE_URL)'
                    DbxWorkspaceRoot: '$(DATABRICKS_WORKSPACE_ROOT)'
                    SubDir: header_footer/databricks/workflows

      - deployment: deployAdWorksWorkflows
        displayName: Deploy Dbx ad_works Workflows
        environment: 'development'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: ../ci/templates/workflows.yml
                  parameters:
                    azureResourceManagerConnection: 'development_subscription'
                    keyVaultName: '$(KEY_VAULT)'
                    SubscriptionId: '$(SUBSCRIPTION_ID)'
                    ResourceGroup: '$(RESOURCE_GROUP)'
                    DbxWorkspaceName: '$(DATABRICKS_WORKSPACE_NAME)'
                    DbxWorkspaceUrl: '$(DATABRICKS_WORKSPACE_URL)'
                    DbxWorkspaceRoot: '$(DATABRICKS_WORKSPACE_ROOT)'
                    SubDir: ad_works/databricks/workflows

      - deployment: deployAdWorksLtWorkflows
        displayName: Deploy Dbx ad_works Workflows
        environment: 'development'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: ../ci/templates/workflows.yml
                  parameters:
                    azureResourceManagerConnection: 'development_subscription'
                    keyVaultName: '$(KEY_VAULT)'
                    SubscriptionId: '$(SUBSCRIPTION_ID)'
                    ResourceGroup: '$(RESOURCE_GROUP)'
                    DbxWorkspaceName: '$(DATABRICKS_WORKSPACE_NAME)'
                    DbxWorkspaceUrl: '$(DATABRICKS_WORKSPACE_URL)'
                    DbxWorkspaceRoot: '$(DATABRICKS_WORKSPACE_ROOT)'
                    SubDir: ad_works_lt/databricks/workflows